// @ts-check
import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { satteri } from '@astrojs/markdown-satteri';
import { SITE, BASE, withBase } from './site.config.mjs';
import { buildLinkDescriptions } from './link-descriptions.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CONTENT_DOCS = path.resolve(__dirname, 'src', 'content', 'docs');

/**
 * Human labels for the section slugs `scripts/sync-docs.mjs` writes. A directory not listed here
 * (a brand new `docs/` subdirectory that has not been mapped) still gets a sidebar group — its
 * label just falls back to a title-cased version of its slug — so the sidebar never needs a config
 * edit to pick up new material.
 */
const KNOWN_LABELS = {
  'getting-started': 'Getting Started',
  api: 'API Reference',
  guides: 'Guides',
  'for-coding-agents': 'For Coding Agents',
  project: 'Project',
};

/**
 * Labels for the sections inside `docs/api/`, which are nested a level deeper than the groups above.
 *
 * Starlight's `autogenerate` labels a nested group with its directory name, so these would read
 * "neural-ai" and "pro-exclusives" in the sidebar. The API reference is the part of the site people
 * navigate most, so its groups get written labels.
 */
const API_SECTION_LABELS = {
  'silicon-compute': 'Silicon & Compute',
  'neural-ai': 'Neural & AI',
  'sensors-actuators': 'Sensors & Actuators',
  'radios-security': 'Radios & Security',
  'system-media': 'System & Media',
  'pro-exclusives': 'Pixel Pro Exclusives',
};

/** Preferred left-to-right order; anything else sorts after, alphabetically. */
const ORDER = ['getting-started', 'api', 'guides', 'for-coding-agents', 'project'];

function titleCase(slug) {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/**
 * Builds the sidebar from whatever section directories `scripts/sync-docs.mjs` actually produced
 * under `src/content/docs/` (itself a mirror of the repo's `docs/` tree — see that script's
 * header comment). Each entry uses Starlight's `autogenerate`, so pages within a section are
 * derived from the directory listing too: add a file under `docs/guides/`, run the sync, and it
 * appears with no change here.
 */
function buildSidebar() {
  if (!existsSync(CONTENT_DOCS)) return [];

  const sections = readdirSync(CONTENT_DOCS, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort((a, b) => {
      const ia = ORDER.indexOf(a);
      const ib = ORDER.indexOf(b);
      if (ia === -1 && ib === -1) return a.localeCompare(b);
      if (ia === -1) return 1;
      if (ib === -1) return -1;
      return ia - ib;
    });

  return sections.map((slug) => ({
    label: KNOWN_LABELS[slug] ?? titleCase(slug),
    items: slug === 'api' ? buildApiItems() : [{ autogenerate: { directory: slug } }],
  }));
}

/**
 * The API group: the index page, then one labelled group per section.
 *
 * Listed explicitly rather than autogenerated so each nested group carries a written label, and so
 * the index sits above the sections instead of being sorted among them. A section directory that
 * appears without a label still shows up, titled from its slug, so adding one needs no edit here.
 */
function buildApiItems() {
  const apiRoot = path.join(CONTENT_DOCS, 'api');
  if (!existsSync(apiRoot)) return [{ autogenerate: { directory: 'api' } }];

  const directories = readdirSync(apiRoot, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name);

  const ordered = [
    ...Object.keys(API_SECTION_LABELS).filter((d) => directories.includes(d)),
    ...directories.filter((d) => !(d in API_SECTION_LABELS)).sort(),
  ];

  return [
    { slug: 'api' },
    ...ordered.map((dir) => ({
      label: API_SECTION_LABELS[dir] ?? titleCase(dir),
      collapsed: true,
      items: [{ autogenerate: { directory: `api/${dir}` } }],
    })),
  ];
}

/**
 * Redirects every page's .md URL to the page itself.
 *
 * The prose is written to be read on GitHub too, so a reader who follows a link from a repository,
 * or types the path they saw in the source tree, arrives at /api/silicon-compute.md and gets a 404.
 * The page exists; only the extension is wrong. Generated from the synced tree rather than
 * hand-listed, so a new page is covered without touching this file.
 */
function buildRedirects() {
  if (!existsSync(CONTENT_DOCS)) return {};
  const out = {};
  const walk = (dir, prefix) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        walk(path.join(dir, entry.name), `${prefix}/${entry.name}`);
        continue;
      }
      if (!/.mdx?$/.test(entry.name)) continue;
      const base = entry.name.replace(/.mdx?$/, '');
      if (base === '404') continue;
      const route = withBase(base === 'index' ? `${prefix}/` : `${prefix}/${base}/`);
      out[`${prefix}/${base}.md`] = route;
    }
  };
  walk(CONTENT_DOCS, '');
  return { ...out, ...RETIRED_ROUTES };
}

/**
 * Pages that were published and then removed, pointed at whatever replaced them.
 *
 * `/api/hardware-api/` was the single page holding all 39 hooks. It is gone: each hook now has its
 * own page, and the two facts that page uniquely carried (the source file path, the verified
 * hardware line) moved onto those pages. The URL was live, so it redirects rather than 404s.
 *
 * The six category URLs are deliberately absent from this list. They still resolve — each is now
 * the section's hub rather than the whole section's prose — so an existing link to
 * `/api/silicon-compute/` still lands somewhere correct.
 */
const RETIRED_ROUTES = {
  '/api/hardware-api': withBase('/api/'),
  '/api/hardware-api.md': withBase('/api/'),
};

/**
 * Wraps every table in a scrolling container.
 *
 * A table needs `overflow-x: auto` so a wide one scrolls instead of pushing the page sideways on a
 * phone. Setting that on the table itself blockifies it: the element then stretches to the content
 * column and takes the border and radius with it, while the rows inside still shrink to fit their
 * text. A narrow table drew a full-width rounded box with the header background and row rules
 * stopping partway across it.
 *
 * Moving the overflow to a wrapper lets the table stay `display: table` and fill its width, so the
 * rows reach the border again.
 *
 * This is a Sätteri hast plugin, not a rehype one: Sätteri is Astro 7's default Markdown processor
 * and does not run the unified pipeline, so `markdown.rehypePlugins` would need
 * `@astrojs/markdown-remark` and would swap the processor for the whole site — including the raw
 * HTML the diagram SVGs are injected as. A filtered visitor returning a replacement node does the
 * same job without changing how anything else is parsed.
 */
const wrapTablesPlugin = {
  name: 'pk-wrap-tables',
  element: {
    filter: ['table'],
    visit(node) {
      // The replacement contains a table, so without this guard the visitor would match its own
      // output and wrap forever.
      if (node.properties?.dataPkWrapped) return;
      return {
        type: 'element',
        tagName: 'div',
        properties: { className: ['pk-table-scroll'] },
        children: [{ ...node, properties: { ...node.properties, dataPkWrapped: 'true' } }],
      };
    },
  },
};

/**
 * Gives every internal link a tooltip saying where it goes.
 *
 * The description is the target page's own first line — or, for a hook page, the same one-line
 * summary the API index shows — so a tooltip can never describe a page differently from the page
 * itself. `src/styles/pixelkit.css` renders `[data-tip]` on hover and on focus.
 *
 * Skipped: links that already carry a tooltip, same-page anchors (the heading is visible on the way
 * there), and anything external. There is no honest description available for an external target,
 * and repeating its domain back at the reader tells them nothing they cannot see in the status bar.
 */
const linkDescriptions = buildLinkDescriptions();

/**
 * Describes the links the Markdown pipeline never sees.
 *
 * The hast plugin below only rewrites page content. The sidebar, the previous/next pagination and
 * the header are Starlight components rendered outside it, and they hold most of the links on the
 * site — about 40 per page in the sidebar alone. This runs once on load and fills them in from the
 * same map, so a reader scanning the sidebar can tell what `useChannelSounding` is without opening
 * it.
 *
 * Two mechanisms on purpose. In the prose column it sets `data-tip`, styled by pixelkit.css. In the
 * chrome it sets `title` and lets the browser draw it: the sidebar is a scroll container, and a CSS
 * tooltip positioned inside one is clipped at its edge. A native tooltip cannot be clipped.
 *
 * Serialised into the page by `toString()`, so it must stay self-contained — no imports, no
 * closure over anything in this file.
 */
function describeChromeLinks(descriptions) {
  function apply() {
    var links = document.querySelectorAll('a[href]');
    for (var i = 0; i < links.length; i += 1) {
      var link = links[i];
      if (link.dataset.tip || link.title) continue;

      var href = link.getAttribute('href');
      if (!href || href.charAt(0) !== '/') continue;

      var pathname = href.split('#')[0];
      var text =
        descriptions[pathname] || descriptions[pathname.replace(/\/$/, '') + '/'];
      if (!text) continue;

      if (link.closest('.sl-markdown-content')) link.dataset.tip = text;
      else link.title = text;
    }
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', apply);
  else apply();
}

const describeLinksPlugin = {
  name: 'pk-describe-links',
  element: {
    filter: ['a'],
    visit(node) {
      const href = node.properties?.href;
      if (typeof href !== 'string' || node.properties?.dataTip) return;
      if (!href.startsWith('/') || href.startsWith('//')) return;

      // Match the page, ignoring any fragment, and tolerate a missing trailing slash.
      const [pathname] = href.split('#');
      const description =
        linkDescriptions.get(pathname) ?? linkDescriptions.get(`${pathname.replace(/\/$/, '')}/`);
      if (!description) return;

      return { ...node, properties: { ...node.properties, dataTip: description } };
    },
  },
};

// https://astro.build/config
export default defineConfig({
  site: SITE,
  base: BASE,
  redirects: buildRedirects(),
  markdown: { processor: satteri({ hastPlugins: [wrapTablesPlugin, describeLinksPlugin] }) },
  integrations: [
    starlight({
      title: 'PixelKit',
      social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/PixelKit-Labs/pixelkit-sdk' }],
      sidebar: buildSidebar(),
      customCss: ['./src/styles/pixelkit.css', './src/styles/archify.css'],
      head: [
        {
          tag: 'script',
          content: `(${describeChromeLinks.toString()})(${JSON.stringify(
            Object.fromEntries(linkDescriptions)
          )});`,
        },
      ],
    }),
  ],
});
