#!/usr/bin/env node
/**
 * @file sync-docs.mjs
 * @description Copies the markdown that already lives in the repo's `docs/` directory into
 * `apps/docs/src/content/docs/`, the directory Starlight's content collection loader reads.
 *
 * `docs/` stays the single source of truth (CLAUDE.md rule 2: a hook change and its documentation
 * update land in the same commit). This script never edits, moves or deletes anything under
 * `docs/` — it only reads it. The copy it produces lives in `src/content/docs/`, which is listed
 * in `.gitignore` and is never committed; it is regenerated by this script before every `dev` and
 * `build` (see package.json), so the rendered site always reflects the current `docs/` tree.
 *
 * The only transformation applied is adding YAML frontmatter when a file does not already have
 * one, because Starlight's page schema requires a `title` field. The title is read from the
 * file's first `# Heading` line. No prose is added, removed or reworded.
 *
 * Run: node scripts/sync-docs.mjs (invoked automatically by `npm run dev` / `npm run build`).
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { BASE, withBase } from '../site.config.mjs';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * The markdown lives in this repository now, at `docs/`. It used to be cloned out of the SDK repo;
 * that made a hook change and its documentation update one commit, but across a repository boundary
 * it also meant the docs could not be edited here. They are the contract now, and the SDK is checked
 * against `data/hooks/*.json` by its own CI, so the source of truth sits here and the code proves it
 * is still true.
 *
 * This script exists only because Starlight requires a `title` in each page's frontmatter and the
 * source files carry none. It copies `docs/` into `src/content/docs/`, which is gitignored and
 * regenerated before every dev run and build, and injects that one field from each file's own first
 * heading. No prose is added, removed or reworded.
 */
const SOURCE_ROOT = path.resolve(__dirname, '..', 'docs');

/** Generated, gitignored: what Starlight's `docsLoader()` reads. */
const TARGET_ROOT = path.resolve(__dirname, '..', 'src', 'content', 'docs');
const DIAGRAM_DIR = path.join(SOURCE_ROOT, 'diagrams');

if (!existsSync(SOURCE_ROOT)) {
  console.error(`sync-docs: source directory not found at ${SOURCE_ROOT}`);
  process.exit(1);
}

/**
 * Top-level files under `docs/` that are not already inside a subdirectory. Each is routed to a
 * specific spot in the generated tree so it sits next to the material it documents, rather than
 * cluttering the site root. Anything under `docs/` not listed here (subdirectories, or a stray
 * top-level file added later) is still picked up: subdirectories are copied as-is by name, and an
 * unlisted top-level `.md` file falls back to the "project" group below.
 *
 * `README.md` is deliberately NOT routed to `index.md`. The site's real homepage is a hand-written
 * page at `src/pages/index.astro` (outside this collection, so this script never touches it). This
 * script wipes and rewrites `TARGET_ROOT` on every run (see below), so anything meant to survive a
 * rebuild has to live outside it; routing README.md anywhere under `index.md` would mean the synced
 * copy and the hand-written page fight over "/" on every build. `readme.md` is unlisted in any
 * sidebar group (like `404.md` below) but still reachable directly for anyone who wants the raw,
 * always-current SDK README.
 */
const TOP_LEVEL_FILE_ROUTES = {
  'README.md': 'readme.md',
  'HARDWARE_API.md': 'api/hardware-api.md',
  'AI_PRIMER.md': 'for-coding-agents/ai-primer.md',
  'PRIVACY.md': 'project/privacy.md',
  'store-listing.md': 'project/store-listing.md',
};

/**
 * Subdirectories of `docs/` are renamed to the section slug they should render under. A source
 * directory not listed here (e.g. a new `docs/whatever/`) is copied through unchanged, so it still
 * appears on the site — see the "site must cover" requirement that the sidebar comes from the
 * directory structure, not a hand-maintained list.
 */
const DIRECTORY_ROUTES = {
  'ai-guidance': 'for-coding-agents',
};

/** The three facts that answer PixelKit's most common support question, rendered above the synced README content at `readme.md`. Generated here, not stored as a second copy of prose that belongs in docs/README.md. */
const LANDING_CALLOUT = `:::caution[Read this first]
- **Android only.** There is no iOS build, and none is planned; every hook is written against Android platform APIs.
- **Requires a development build.** PixelKit cannot run inside Expo Go — it ships two native Expo Modules (\`@pixelkit-labs/native\`, \`@pixelkit-labs/mlkit\`) that Expo Go does not include. Build a dev client with EAS or a local Gradle build.
- **Most hooks are Pixel-specific by design.** Off a Pixel 11 Pro, a hook that cannot read real hardware reports \`source: 'unavailable'\` and returns \`null\` rather than a fabricated number. In the UI that renders as an em dash ("—"), never a plausible-looking placeholder value.
:::

`;

function titleCase(slug) {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/** Reads the first `# Heading` line of a markdown file for use as its Starlight page title. */
function deriveTitle(markdown, fallbackSlug) {
  const match = markdown.match(/^#\s+(.+)$/m);
  if (match) return match[1].trim();
  return titleCase(path.basename(fallbackSlug, '.md'));
}

/** True when the file already starts with a YAML frontmatter block. */
function hasFrontmatter(markdown) {
  return /^---\r?\n/.test(markdown);
}

/**
 * Substitutes `<!-- diagram: name -->` with the committed SVG at `docs/diagrams/name.svg`.
 *
 * Markdown carries the placeholder rather than 11 kB of inline SVG so the source stays readable and
 * a diagram change shows up as a diff of its spec, not of the prose around it. The SVG is coloured
 * by `src/styles/archify.css` through `[data-theme]`, so it follows the site's light/dark toggle.
 *
 * A placeholder naming a diagram that does not exist throws. The alternative — leaving the comment
 * in place — publishes a page with a silently missing figure, which is exactly how the ASCII
 * diagrams rotted without anyone noticing.
 */
function injectDiagrams(markdown, sourcePath) {
  return markdown.replace(/^[ \t]*<!--\s*diagram:\s*([a-z0-9-]+)\s*-->[ \t]*$/gm, (_match, name) => {
    const svgPath = path.join(DIAGRAM_DIR, `${name}.svg`);
    if (!existsSync(svgPath)) {
      throw new Error(
        `${sourcePath}: <!-- diagram: ${name} --> has no docs/diagrams/${name}.svg. ` +
          'Add the spec and run `npm run build:diagrams`.'
      );
    }
    // The inlined copy is flattened: blank lines removed and every line de-indented. Both matter to
    // the markdown parser rather than to appearance. A markdown HTML block ends at the first blank
    // line, and a line indented four spaces or more starts an indented code block - archify indents
    // its SVG up to twelve. Left as-is, the parser keeps <figure>, <svg>, <title> and <defs>, then
    // silently drops every lane, node and edge after </defs>, rendering a correctly sized but empty
    // box. The file on disk keeps its formatting.
    const svg = readFileSync(svgPath, 'utf8')
      .split(/\r?\n/)
      .filter((line) => line.trim() !== '')
      .map((line) => line.trimStart())
      .join('\n');
    return `<figure class="archify-figure">\n${svg}\n</figure>`;
  });
}

/**
 * Maps a path inside `docs/` to the URL the site serves it at, using the same two route tables the
 * copy below uses. Returns null when the file does not exist, which is how a dead link is caught.
 */
function docsPathToUrl(relativeFromDocs) {
  const normalised = relativeFromDocs.split(path.sep).join('/');
  if (!existsSync(path.join(SOURCE_ROOT, normalised))) return null;

  const segments = normalised.split('/');
  let route;

  if (segments.length === 1) {
    route = TOP_LEVEL_FILE_ROUTES[segments[0]] ?? `project/${segments[0]}`;
  } else {
    const [dir, ...rest] = segments;
    const mapped = DIRECTORY_ROUTES[dir] ?? dir;
    const last = rest[rest.length - 1] === 'README.md' ? 'index.md' : rest[rest.length - 1];
    route = [mapped, ...rest.slice(0, -1), last].join('/');
  }

  const withoutExtension = route.replace(/\.mdx?$/, '');
  const asDirectory = withoutExtension.replace(/\/index$/, '');
  return withBase(`/${asDirectory}/`);
}

/**
 * Rewrites relative `.md` links to the URLs the site actually serves.
 *
 * The prose is written to be read on GitHub as well as here, so links between pages are relative
 * file paths — `./quickstart.md`, `../api/neural-ai.md`. Starlight serves those pages at extensionless
 * directory URLs, so every one of them 404s on the site. There were 82 across 10 pages, and nothing
 * reported them because a markdown link to a missing page is not a build error.
 *
 * A link whose target does not exist under `docs/` throws rather than being rewritten into a URL
 * that would also 404 — a dead cross-reference should fail the build, not get tidier.
 */
function rewriteLinks(markdown, sourcePath) {
  const fromDir = path.dirname(path.relative(SOURCE_ROOT, sourcePath));

  // Site-absolute links written straight into the prose, like `](/api/)`. They need the base as
  // much as a generated link does, and neither rule below matches them because they are not file
  // links and not relative. Already-prefixed links are left alone so this stays idempotent.
  const withAbsolute = markdown.replace(/\]\((\/[a-z0-9][^)\s#]*)(#[^)\s]*)?\)/g, (match, target, anchor = '') => {
    if (target.startsWith(`${BASE.replace(/\/$/, '')}/`)) return match;
    return `](${withBase(target)}${anchor})`;
  });

  // Directory links first. `./api/` is not a file link, so the rule below never sees it, and a
  // browser resolves it against the *current URL* rather than the source tree: from /readme/ it
  // becomes /readme/api/, which 404s. All four section links on the docs landing page were dead
  // this way, including ./ai-guidance/, whose section is served at /for-coding-agents/.
  const withDirectories = withAbsolute.replace(/\]\((\.{1,2}\/)([a-z0-9-]+)\/\)/g, (match, _prefix, dir) => {
    if (!existsSync(path.join(SOURCE_ROOT, dir))) return match;
    return `](${withBase(`/${DIRECTORY_ROUTES[dir] ?? dir}/`)})`;
  });

  return withDirectories.replace(/\]\((\.{1,2}\/[^)\s#]+?\.mdx?|[^)\s#:]+?\.mdx?)(#[^)\s]*)?\)/g, (match, target, anchor = '') => {
    // Absolute paths and anything outside docs/ are left alone: they point at the repository, not
    // at a page on this site.
    if (target.startsWith('/')) return match;

    // A relative link that climbs out of docs/ points at a repository file with no page on this
    // site, so it 404s for every reader. `../RELEASING.md` was exactly that. There is no correct
    // rewrite — the target genuinely is not published here — so it has to become an absolute URL.
    const resolved = path.normalize(path.join(fromDir, target));
    if (resolved.startsWith('..')) {
      throw new Error(
        `${path.relative(SOURCE_ROOT, sourcePath)}: link to "${target}" points outside docs/, so it ` +
          'has no page on this site. Use an absolute https:// URL to the file on GitHub.'
      );
    }

    const url = docsPathToUrl(resolved);
    if (!url) {
      throw new Error(
        `${path.relative(SOURCE_ROOT, sourcePath)}: link to "${target}" has no such file under docs/. ` +
          'Fix the link, or point it at the repository with an absolute URL.'
      );
    }
    return `](${url}${anchor})`;
  });
}

function copyMarkdownFile(sourcePath, targetPath, { landingCallout = false } = {}) {
  const raw = rewriteLinks(injectDiagrams(readFileSync(sourcePath, 'utf8'), sourcePath), sourcePath);
  let out;

  if (hasFrontmatter(raw)) {
    out = raw;
  } else {
    const titleMatch = raw.match(/^#\s+(.+)$/m);
    const title = (titleMatch ? titleMatch[1].trim() : deriveTitle(raw, targetPath)).replace(/"/g, '\\"');
    const frontmatter = `---\ntitle: "${title}"\n---\n\n`;
    // Starlight already renders `title` as the page heading, so the same line in the body would
    // be a duplicate <h1>. It is removed only from this generated copy, not from the docs/ source.
    const body = titleMatch ? raw.slice(0, titleMatch.index) + raw.slice(titleMatch.index + titleMatch[0].length + 1) : raw;
    out = frontmatter + (landingCallout ? LANDING_CALLOUT : '') + body;
  }

  mkdirSync(path.dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, out, 'utf8');
}

function copyDirectory(sourceDir, targetDir) {
  for (const entry of readdirSync(sourceDir, { withFileTypes: true })) {
    const sourcePath = path.join(sourceDir, entry.name);
    if (entry.isDirectory()) {
      copyDirectory(sourcePath, path.join(targetDir, entry.name));
      continue;
    }
    if (!entry.name.endsWith('.md') && !entry.name.endsWith('.mdx')) continue;
    // A README.md inside a section directory becomes that section's own landing page.
    const targetName = entry.name === 'README.md' ? 'index.md' : entry.name;
    copyMarkdownFile(sourcePath, path.join(targetDir, targetName));
  }
}

// Start clean so a file removed from docs/ does not linger in the generated site.
rmSync(TARGET_ROOT, { recursive: true, force: true });
mkdirSync(TARGET_ROOT, { recursive: true });

// Starlight looks up a "404" entry in the docs collection for its not-found page; without one it
// still builds but warns. This is generated site chrome, not documentation content, so it is
// written directly rather than sourced from docs/.
writeFileSync(
  path.join(TARGET_ROOT, '404.md'),
  '---\ntitle: "Not found"\ntemplate: splash\n---\n\nThat page does not exist. Use the sidebar or search to find what you need.\n',
  'utf8',
);

for (const entry of readdirSync(SOURCE_ROOT, { withFileTypes: true })) {
  const sourcePath = path.join(SOURCE_ROOT, entry.name);

  if (entry.isDirectory()) {
    const targetDirName = DIRECTORY_ROUTES[entry.name] ?? entry.name;
    copyDirectory(sourcePath, path.join(TARGET_ROOT, targetDirName));
    continue;
  }

  if (!entry.name.endsWith('.md')) continue;

  const route = TOP_LEVEL_FILE_ROUTES[entry.name] ?? path.join('project', entry.name);
  const targetPath = path.join(TARGET_ROOT, route);
  copyMarkdownFile(sourcePath, targetPath, { landingCallout: route === 'readme.md' });
}

/** Recursively counts the markdown files actually written, for the console summary below. */
function countMarkdown(dir) {
  let n = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) n += countMarkdown(full);
    else if (entry.name.endsWith('.md') || entry.name.endsWith('.mdx')) n += 1;
  }
  return n;
}

const filesCopied = countMarkdown(TARGET_ROOT);
console.log(`sync-docs: wrote ${filesCopied} page(s) from ${SOURCE_ROOT} to ${TARGET_ROOT}`);
