#!/usr/bin/env node
/**
 * @file sync-docs.mjs
 * @description Copies the markdown that already lives in the repo's `docs/` directory into
 * `apps/docs/src/content/docs/`, the directory Starlight's content collection loader reads.
 *
 * `docs/` stays the single source of truth (CLAUDE.md rule 2: a hook change and its documentation
 * update land in the same commit). This script never edits, moves or deletes anything under
 * `docs/` — it only reads it. The copy it produces lives in `src/content/docs/`, which is listed
 * in `.gitignore` and is never committed; it is regenerated by this script before every `dev` and
 * `build` (see package.json), so the rendered site always reflects the current `docs/` tree.
 *
 * The only transformation applied is adding YAML frontmatter when a file does not already have
 * one, because Starlight's page schema requires a `title` field. The title is read from the
 * file's first `# Heading` line. No prose is added, removed or reworded.
 *
 * Run: node scripts/sync-docs.mjs (invoked automatically by `npm run dev` / `npm run build`).
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * The markdown lives in this repository now, at `docs/`. It used to be cloned out of the SDK repo;
 * that made a hook change and its documentation update one commit, but across a repository boundary
 * it also meant the docs could not be edited here. They are the contract now, and the SDK is checked
 * against `data/hooks/*.json` by its own CI, so the source of truth sits here and the code proves it
 * is still true.
 *
 * This script exists only because Starlight requires a `title` in each page's frontmatter and the
 * source files carry none. It copies `docs/` into `src/content/docs/`, which is gitignored and
 * regenerated before every dev run and build, and injects that one field from each file's own first
 * heading. No prose is added, removed or reworded.
 */
const SOURCE_ROOT = path.resolve(__dirname, '..', 'docs');

/** Generated, gitignored: what Starlight's `docsLoader()` reads. */
const TARGET_ROOT = path.resolve(__dirname, '..', 'src', 'content', 'docs');

if (!existsSync(SOURCE_ROOT)) {
  console.error(`sync-docs: source directory not found at ${SOURCE_ROOT}`);
  process.exit(1);
}

/**
 * Top-level files under `docs/` that are not already inside a subdirectory. Each is routed to a
 * specific spot in the generated tree so it sits next to the material it documents, rather than
 * cluttering the site root. Anything under `docs/` not listed here (subdirectories, or a stray
 * top-level file added later) is still picked up: subdirectories are copied as-is by name, and an
 * unlisted top-level `.md` file falls back to the "project" group below.
 *
 * `README.md` is deliberately NOT routed to `index.md`. The site's real homepage is a hand-written
 * page at `src/pages/index.astro` (outside this collection, so this script never touches it). This
 * script wipes and rewrites `TARGET_ROOT` on every run (see below), so anything meant to survive a
 * rebuild has to live outside it; routing README.md anywhere under `index.md` would mean the synced
 * copy and the hand-written page fight over "/" on every build. `readme.md` is unlisted in any
 * sidebar group (like `404.md` below) but still reachable directly for anyone who wants the raw,
 * always-current SDK README.
 */
const TOP_LEVEL_FILE_ROUTES = {
  'README.md': 'readme.md',
  'HARDWARE_API.md': 'api/hardware-api.md',
  'AI_PRIMER.md': 'for-coding-agents/ai-primer.md',
  'PRIVACY.md': 'project/privacy.md',
  'store-listing.md': 'project/store-listing.md',
};

/**
 * Subdirectories of `docs/` are renamed to the section slug they should render under. A source
 * directory not listed here (e.g. a new `docs/whatever/`) is copied through unchanged, so it still
 * appears on the site — see the "site must cover" requirement that the sidebar comes from the
 * directory structure, not a hand-maintained list.
 */
const DIRECTORY_ROUTES = {
  'ai-guidance': 'for-coding-agents',
};

/** The three facts that answer PixelKit's most common support question, rendered above the synced README content at `readme.md`. Generated here, not stored as a second copy of prose that belongs in docs/README.md. */
const LANDING_CALLOUT = `:::caution[Read this first]
- **Android only.** There is no iOS build, and none is planned; every hook is written against Android platform APIs.
- **Requires a development build.** PixelKit cannot run inside Expo Go — it ships two native Expo Modules (\`@pixelkit-labs/native\`, \`@pixelkit-labs/mlkit\`) that Expo Go does not include. Build a dev client with EAS or a local Gradle build.
- **Most hooks are Pixel-specific by design.** Off a Pixel 11 Pro, a hook that cannot read real hardware reports \`source: 'unavailable'\` and returns \`null\` rather than a fabricated number. In the UI that renders as an em dash ("—"), never a plausible-looking placeholder value.
:::

`;

function titleCase(slug) {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/** Reads the first `# Heading` line of a markdown file for use as its Starlight page title. */
function deriveTitle(markdown, fallbackSlug) {
  const match = markdown.match(/^#\s+(.+)$/m);
  if (match) return match[1].trim();
  return titleCase(path.basename(fallbackSlug, '.md'));
}

/** True when the file already starts with a YAML frontmatter block. */
function hasFrontmatter(markdown) {
  return /^---\r?\n/.test(markdown);
}

function copyMarkdownFile(sourcePath, targetPath, { landingCallout = false } = {}) {
  const raw = readFileSync(sourcePath, 'utf8');
  let out;

  if (hasFrontmatter(raw)) {
    out = raw;
  } else {
    const titleMatch = raw.match(/^#\s+(.+)$/m);
    const title = (titleMatch ? titleMatch[1].trim() : deriveTitle(raw, targetPath)).replace(/"/g, '\\"');
    const frontmatter = `---\ntitle: "${title}"\n---\n\n`;
    // Starlight already renders `title` as the page heading, so the same line in the body would
    // be a duplicate <h1>. It is removed only from this generated copy, not from the docs/ source.
    const body = titleMatch ? raw.slice(0, titleMatch.index) + raw.slice(titleMatch.index + titleMatch[0].length + 1) : raw;
    out = frontmatter + (landingCallout ? LANDING_CALLOUT : '') + body;
  }

  mkdirSync(path.dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, out, 'utf8');
}

function copyDirectory(sourceDir, targetDir) {
  for (const entry of readdirSync(sourceDir, { withFileTypes: true })) {
    const sourcePath = path.join(sourceDir, entry.name);
    if (entry.isDirectory()) {
      copyDirectory(sourcePath, path.join(targetDir, entry.name));
      continue;
    }
    if (!entry.name.endsWith('.md') && !entry.name.endsWith('.mdx')) continue;
    // A README.md inside a section directory becomes that section's own landing page.
    const targetName = entry.name === 'README.md' ? 'index.md' : entry.name;
    copyMarkdownFile(sourcePath, path.join(targetDir, targetName));
  }
}

// Start clean so a file removed from docs/ does not linger in the generated site.
rmSync(TARGET_ROOT, { recursive: true, force: true });
mkdirSync(TARGET_ROOT, { recursive: true });

// Starlight looks up a "404" entry in the docs collection for its not-found page; without one it
// still builds but warns. This is generated site chrome, not documentation content, so it is
// written directly rather than sourced from docs/.
writeFileSync(
  path.join(TARGET_ROOT, '404.md'),
  '---\ntitle: "Not found"\ntemplate: splash\n---\n\nThat page does not exist. Use the sidebar or search to find what you need.\n',
  'utf8',
);

for (const entry of readdirSync(SOURCE_ROOT, { withFileTypes: true })) {
  const sourcePath = path.join(SOURCE_ROOT, entry.name);

  if (entry.isDirectory()) {
    const targetDirName = DIRECTORY_ROUTES[entry.name] ?? entry.name;
    copyDirectory(sourcePath, path.join(TARGET_ROOT, targetDirName));
    continue;
  }

  if (!entry.name.endsWith('.md')) continue;

  const route = TOP_LEVEL_FILE_ROUTES[entry.name] ?? path.join('project', entry.name);
  const targetPath = path.join(TARGET_ROOT, route);
  copyMarkdownFile(sourcePath, targetPath, { landingCallout: route === 'readme.md' });
}

/** Recursively counts the markdown files actually written, for the console summary below. */
function countMarkdown(dir) {
  let n = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) n += countMarkdown(full);
    else if (entry.name.endsWith('.md') || entry.name.endsWith('.mdx')) n += 1;
  }
  return n;
}

const filesCopied = countMarkdown(TARGET_ROOT);
console.log(`sync-docs: wrote ${filesCopied} page(s) from ${SOURCE_ROOT} to ${TARGET_ROOT}`);
